### ISSUE TITLE
Condition variable deadlock

### ISSUE THREAD

**Issue by aalri** [jhoffman0x/Box2D-MT#6]
b2Threading.cpp#line_92 m_taskAddedCond.notify_all(); will eventually cause condition variable deadlock. 

Recommend moving it inside the mutex block above it. 

Also do the same thing to b2Threading.cpp#line_103 m_taskAddedCond.notify_one();

Reference: [https://stackoverflow.com/questions/15912322/condition-variable-deadlock](https://stackoverflow.com/questions/15912322/condition-variable-deadlock)

**Comment by skitzoid** [comment]
Did you actually observe a deadlock? If so please provide call stacks for the deadlocked threads.

In general the mutex doesn't need to be locked during a call to condition variable's notify. In this case it's locked before the notify, while tasks are being added, and it's locked by the waiting threads while checking if tasks have been added. I could be wrong but this seems sufficient.

**Comment by jhoffman0x** [comment]
In your reference, the problem wasn't that they didn't hold a lock while notifying, but that they didn't use another object to represent whether the event occurred.

You can create another issue if you really saw a deadlock.
